/**
 * exportInventoryReportPDF.js
 * Client-side PDF export for the Inventory > Reports page, mirroring the
 * roster's exportPDF.js pattern (same jsPDF + jspdf-autotable already used
 * there — no new dependency needed).
 *
 * Every PDF is stamped with who generated it and when, both in the header
 * and repeated in the footer of every page.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * @param {string} title - report title, e.g. "Stock Movement Totals"
 * @param {string[]} columns - table header labels
 * @param {(string|number)[][]} rows - table body rows
 * @param {string} generatedBy - display name/email of the user exporting the report
 * @param {string} [filtersLabel] - human-readable summary of active filters (department, date range)
 */
export function exportReportPDF({ title, columns, rows, generatedBy, filtersLabel }) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
  const now = new Date();
  const generatedOn = now.toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' });

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text(title, 40, 44);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated by: ${generatedBy}`, 40, 64);
  doc.text(`Generated on: ${generatedOn}`, 40, 78);
  if (filtersLabel) {
    doc.text(filtersLabel, 40, 92);
  }

  autoTable(doc, {
    head: [columns],
    body: rows,
    startY: filtersLabel ? 106 : 92,
    theme: 'grid',
    styles: {
      fontSize: 9,
      cellPadding: 6,
      lineColor: [226, 232, 240],
      lineWidth: 0.5,
    },
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
  });

  // Stamp every page's footer, not just the first — so the provenance
  // (who/when) survives even if the table spans multiple pages.
  const pageCount = doc.internal.getNumberOfPages();
  const pageHeight = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by ${generatedBy} on ${generatedOn}`, 40, pageHeight - 20);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.getWidth() - 80, pageHeight - 20);
  }

  const stamp = now.toISOString().slice(0, 10);
  const safeTitle = title.replace(/\s+/g, '_').toLowerCase();
  doc.save(`${safeTitle}_${stamp}.pdf`);
}
